apiVersion: v1
kind: Service
metadata:
  name: llm-minio-console-nodeport
  namespace: llm-platform
spec:
  type: NodePort
  selector:
    v1.min.io/tenant: llm-minio
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 32002
---
apiVersion: v1
kind: Service
metadata:
  name: llm-minio-api-nodeport
  namespace: llm-platform
spec:
  type: NodePort
  selector:
    v1.min.io/tenant: llm-minio
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 32001
